### ISSUE TITLE
CasperJs not working

### ISSUE THREAD

**Issue by fahadacheema** [alwex/php-casperjs#49]
I installed this package and followed all the steps mentioned in the git but it still doesn't work and keeps giving me the error `"Can not find CasperJS."`. I know many people have raised this issue before as well and I've tried all the solutions suggested to fix this problem but no luck. Can someone please tell me step by step how can I make this work in my Laravel Application. Am I missing something?

**Comment by antoiba86** [comment]
Did you try this?
https://github.com/alwex/php-casperjs/issues/41

The error can not find casperjs make that tere are so many possibilities. But the regular problems are because casperjs is not installed properly as system variable. Or php-casperjs cannot find the path to casper or it could be that casperjs cannot find the path to phantomjs.
Is it Windows or a Linux system?
